- name: Deploy EMR System on AWS
  hosts: all
  become: true
  tasks:

    - name: Update and install required packages
      apt:
        update_cache: yes
        name:
          - apache2
          - mysql-server
          - php
          - libapache2-mod-php
          - php-mysql
          - git
        state: present

    - name: Start and enable Apache and MySQL
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - mysql

    - name: Remove existing project directory
      file:
        path: "/var/www/html"
        state: absent

    - name: Clone the project from GitHub
      git:
        repo: "https://github.com/Dipak-Kalaskar077/Final-Year-Project.git"
        dest: "/var/www/html"
        force: yes

    - name: Set proper permissions for project files
      file:
        path: "/var/www/html"
        owner: www-data
        group: www-data
        mode: "0755"
        recurse: yes

    - name: Install required Python MySQL dependencies
      apt:
        name: python3-pymysql
        state: present

    - name: Configure MySQL Database
      become: true
      shell: |
        mysql -u root -e "DROP DATABASE IF EXISTS edoc;"
        mysql -u root -e "CREATE DATABASE edoc;"
        mysql -u root -e "DROP USER IF EXISTS 'edoc_user'@'localhost';"
        mysql -u root -e "CREATE USER 'edoc_user'@'localhost' IDENTIFIED BY 'dipak@2424.';"
        mysql -u root -e "GRANT ALL PRIVILEGES ON edoc.* TO 'edoc_user'@'localhost';"
        mysql -u root -e "FLUSH PRIVILEGES;"

    - name: Import database schema if file exists
      shell: |
        if [ -f /var/www/html/SQL_Database_edoc.sql ]; then
          mysql -u root edoc < /var/www/html/SQL_Database_edoc.sql;
        fi
      become: true
      ignore_errors: yes

    - name: Create connection.php with database credentials
      copy:
        dest: "/var/www/html/connection.php"
        content: |
          <?php
          $host = 'localhost';
          $username = 'edoc_user';
          $password = 'dipak@2424.';
          $dbname = 'edoc';

          $database = new mysqli($host, $username, $password, $dbname);

          if ($database->connect_error) {
              die('Connection failed: ' . $database->connect_error);
          }
          ?>
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Restart Apache to apply changes
      systemd:
        name: apache2
        state: restarted
